### ISSUE TITLE
容器卡住了

### ISSUE THREAD

**Issue by wangyunqing198801** [wuzhi04/MyActions#1]
========================1. 更新源代码========================

crond[9]: crond (busybox 1.31.1) started, log level 8

--------------------------------------------------------------

系统时间：2021-06-08 14:46:22

JS脚本目录：/jd/scripts

--------------------------------------------------------------

更新shell...

Fetching origin

HEAD is now at 64dee5e Update git_pull.sh

更新shell成功...

更新脚本

Fetching origin

**Comment by wuzhi04** [comment]
删除scripts文件夹
