### ISSUE TITLE
过期的活动&错误的活动

### ISSUE THREAD

**Issue by stspqxl** [wuzhi04/MyActions#10]
过期的活动
jd_618Opencard07

错误的活动
jd_ShopSign
jd_beauty
jd_crazy_joy_bonus
jd_joy
jd_joy_feedPets 喂养无效
jd_joy_reward
jd_jxmc
jd_qqtmy
jd_rankingList

**Comment by lotusxhaofda001** [comment]
jd_necklace也是无效了，19号JD更新了

**Comment by wuzhi04** [comment]
好的 今天都暂时撤下来
