### ISSUE TITLE
脚本更新

### ISSUE THREAD

**Issue by stspqxl** [wuzhi04/MyActions#14]
1、jd_carnivalcity 手机狂欢城已经结束；
2、十元街 jd_syj.js 增加赚京豆-瓜分京豆开关，一些可以手动助理的朋友可以关闭自动助力，避免半夜运行浪费开团次数
config.sh增加
## 设置为 false 时，十元街不自动开团
SYJ_CAN_DISTRIBUTEBEAN=""

https://raw.githubusercontent.com/stspqxl/act/main/jd_syj.js

**Comment by wuzhi04** [comment]
好的 有时间看看
