### ISSUE TITLE
大佬 请问新库如何让my action 自动开始完成任务 

### ISSUE THREAD

**Issue by Tiklivile1994** [wuzhi04/MyActions#15]
昨天库被封了  不能用自动功能了  注册一个新库 手动激发一次自动同步以后  如何让这些脚本按时间自动运行 
如果star一下的话 会把所有脚本跑一遍 然后我的账户就被秒封了  
麻烦大佬了  实在是不懂编程  只能请教你了

**Comment by wuzhi04** [comment]
你不点star他到点就会运行，但是目前github封库严重 还是不要用的好，准备云函数或者找个设备部署docker吧
