### ISSUE TITLE
QQ星牧场

### ISSUE THREAD

**Issue by wangyunqing198801** [wuzhi04/MyActions#16]
https://github.com/DovFork/Wenmoux/blob/master/jd/jd_qqxing.js

**Comment by wangyunqing198801** [comment]
https://github.com/passerby-b/JDDJ/blob/main/jddj_fruit.js京东到家果园

**Comment by wangyunqing198801** [comment]
https://github.com/passerby-b/JDDJ
京东到家脚本合集

**Comment by tabs** [comment]
牛批我的哥，赶紧合并吧，我这伸手党等着。。。

**Comment by wuzhi04** [comment]
好的有时间看看
