### ISSUE TITLE
大佬，有脚本，能更新进去吗？

### ISSUE THREAD

**Issue by Acczar** [wuzhi04/MyActions#18]
青龙拉取常用京东脚本库，公众号少年歌行pro整理

6月16日可用

【某不愿透露姓名大佬】

ql repo https://github.com/chinnkarahoi/jd_scripts.git "jd_|jx_|getJDCookie" "activity|backUp" "^jd[^_]|USER"

【龙珠】
ql repo https://github.com/longzhuzhu/nianyu.git "qx" “main”

【混沌】
ql repo https://github.com/whyour/hundun.git "quanx" "tokens|caiyun|didi|donate|fold|Env"

【passerby-b】（需要配合专用ck文件）
ql repo https://github.com/passerby-b/JDDJ.git "jddj_" "scf_test_event" "jddj_cookie"

【温某人】

青龙拉取常用京东脚本库，公众号少年歌行pro整理

6月16日可用

【某不愿透露姓名大佬】

ql repo https://github.com/chinnkarahoi/jd_scripts.git "jd_|jx_|getJDCookie" "activity|backUp" "^jd[^_]|USER"

【龙珠】
ql repo https://github.com/longzhuzhu/nianyu.git "qx" “main”

【混沌】
ql repo https://github.com/whyour/hundun.git "quanx" "tokens|caiyun|didi|donate|fold|Env"

【passerby-b】（需要配合专用ck文件）
ql repo https://github.com/passerby-b/JDDJ.git "jddj_" "scf_test_event" "jddj_cookie"

【温某人】

ql repo https://github.com/Wenmoux/scripts.git  "jd" "" "" "wen"

【柠檬（胖虎）】
ql repo https://github.com/panghu999/panghu.git "jd_"

【zoopanda（动物园）】
ql repo https://github.com/zooPanda/zoo.git "zoo"

【Ariszy（Zhiyi-N）】

ql repo https://github.com/Ariszy/Private-Script.git "JD"

【ddo（hyzaw）】

ql repo https://github.com/hyzaw/scripts.git "ddo_"

【star261】

ql repo https://github.com/star261/jd.git "scripts" "code" 

【翻翻乐提现单文件】

ql raw https://raw.githubusercontent.com/jiulan/platypus/main/scripts/jd_ffl.js

【zcy01】

ql repo https://github.com/ZCY01/daily_scripts.git "jd_"

#公众号少年歌行pro
#青龙面板
https://t.me/shao66

【柠檬（胖虎）】
ql repo https://github.com/panghu999/panghu.git "jd_"

【zoopanda（动物园）】
ql repo https://github.com/zooPanda/zoo.git "zoo"

【Ariszy（Zhiyi-N）】

ql repo https://github.com/Ariszy/Private-Script.git "JD"

【ddo（hyzaw）】

ql repo https://github.com/hyzaw/scripts.git "ddo_"

【star261】

ql repo https://github.com/star261/jd.git "scripts" "code" 

【翻翻乐提现单文件】

ql raw https://raw.githubusercontent.com/jiulan/platypus/main/scripts/jd_ffl.js

【zcy01】

ql repo https://github.com/ZCY01/daily_scripts.git "jd_"

#公众号少年歌行pro
#青龙面板
https://t.me/shao66

**Comment by wuzhi04** [comment]
有需要加进去的我会加，一些无收益或者收益很低的个别脚本暂时不会考虑

**Comment by stspqxl** [comment]
有个星球牧场，没找到脚本。
