### ISSUE TITLE
自动更新容器失败怎么回事儿，直接在portainer里点拉取也不更新

### ISSUE THREAD

**Issue by openwrt-try** [wuzhi04/MyActions#2]
time="2021-06-15T12:52:52Z" level=info msg="Watchtower 1.3.0\nUsing no notifications\nOnly checking containers with name \"jd\"\nScheduling first run: 2021-06-15 13:03:00 +0000 UTC\nNote that the first check will be performed in 10 minutes, 7 seconds"

time="2021-06-15T13:03:00Z" level=warning msg="Could not do a head request for \"shuye72/jd-base:gitee\", falling back to regular pull." container=/jd image="shuye72/jd-base:gitee"

time="2021-06-15T13:03:00Z" level=warning msg="Reason: Get \"https://index.docker.io/v2/\": dial tcp 34.202.206.152:443: connect: connection refused" container=/jd image="shuye72/jd-base:gitee"

**Comment by wuzhi04** [comment]
不清楚
