### ISSUE TITLE
求助，js-base面板问题

### ISSUE THREAD

**Issue by qilin008** [wuzhi04/MyActions#23]
装的win版docker，部署好了，但是面板打不开，然后以为是端口占用，检查5678端口占用情况一个进程
也没有

![image](https://user-images.githubusercontent.com/78195056/121614160-b377b400-ca90-11eb-9867-2997f0524116.png)

**Comment by xuexijiaoben** [comment]
我也打不开， 按命令下载镜像、部署之后，总是重启，不知道命令哪儿错了，下载镜像，再用docker这个软件打开容器到时成功运行了，也是没有面板，关键是自动运行的脚本好像不管用，京东里没有任何变化，尝试手动运行了下签到，京东里有变化，不知道为什么，
兄弟解决了来这里回复一下呀，一块儿学习

**Comment by wuzhi04** [comment]
win docker自行研究 命令不太一样

**Comment by anakinlee99** [comment]
windows docker的地址是   localhost:5678
