### ISSUE TITLE
action现在跑不了了吗，之前的被ban了，新建的号只要设置同步脚本马上就被封号了

### ISSUE THREAD

**Issue by qiubeiliana** [wuzhi04/MyActions#25]
action现在跑不了了吗，之前的被ban了，新建的号只要设置同步脚本马上就被封号了，大佬考虑转其他方式吗，比如腾讯云之类的

**Comment by Eva-Joker** [comment]
说了多少次了，不要fork,不要用github action。 去搞个云服务器然后linux部署个docker不好么？

**Comment by sunjianbo** [comment]
> 说了多少次了，不要fork,不要用github action。 去搞个云服务器然后linux部署个docker不好么？

docker链接的库显示项目废弃了

**Comment by wuzhi04** [comment]
多动脑子多实践

**Comment by wangyunqing198801** [comment]
> > 说了多少次了，不要fork,不要用github action。 去搞个云服务器然后linux部署个docker不好么？
> 
> docker链接的库显示项目废弃了

不要在意细节，跑就对了。
