### ISSUE TITLE
如何同步更新？

### ISSUE THREAD

**Issue by tiddlerhxy** [wuzhi04/MyActions#27]
您好，您更新脚本后我部署在云主机的服务如何同步更新？

**Comment by tabs** [comment]
git fetch

**Comment by tiddlerhxy** [comment]
> git fetch

**Comment by tiddlerhxy** [comment]
> git fetch

只需要拉代码是吗？
容器里会自动更新是吗？

**Comment by tiddlerhxy** [comment]
![image](https://user-images.githubusercontent.com/34333691/123195611-0e6ec980-d4db-11eb-906a-08f9b9611db3.png)
这个是自动更新吧，部署了就不用自己做同步了
