### ISSUE TITLE
大佬帮忙看看为什么互助不了啊

### ISSUE THREAD

**Issue by 1668458964** [wuzhi04/MyActions#27]
所有需要填互助码的都这样
![QQ截图20210611143845](https://user-images.githubusercontent.com/58337621/121642772-8ee8ff80-cac3-11eb-85cb-78a80ea27693.png)
![QQ截图20210611143900](https://user-images.githubusercontent.com/58337621/121642776-901a2c80-cac3-11eb-92ca-938edd8a568c.png)
![QQ截图20210611143706](https://user-images.githubusercontent.com/58337621/121642783-91e3f000-cac3-11eb-97bf-5991063e7bfe.png)

**Comment by 1668458964** [comment]
我知道了   面板里填写的互助码没保存进脚本   config.sh里面只有ck  所有互助码都是空白的 能修复一下吗 还是只能自行进脚本填写

**Comment by wuzhi04** [comment]
自己去多读几遍config最下方的填写示例就会写了，面板没问题你自己理解有问题
