### ISSUE TITLE
大佬 我帮你同步

### ISSUE THREAD

**Issue by tabs** [wuzhi04/MyActions#28]
https://github.com/JDHelloWorld/jd_scripts

大佬你最近忙  我准备 pull request上面的同步更新，在修改了

**Comment by tiddlerhxy** [comment]
👍

**Comment by zwy98280** [comment]
> https://github.com/JDHelloWorld/jd_scripts
> 
> 大佬你最近忙我准备拉请求上面的同步更新，在修改了

大佬怎么同步这个呀？

**Comment by wuzhi04** [comment]
没事我回头有时间看commit记录就行了

**Comment by tabs** [comment]
> > https://github.com/JDHelloWorld/jd_scripts
> > 大佬你最近忙我准备拉请求上面的同步更新，在修改了
> 
> 大佬怎么同步这个呀？



> > https://github.com/JDHelloWorld/jd_scripts
> > 大佬你最近忙我准备拉请求上面的同步更新，在修改了
> 
> 大佬怎么同步这个呀？

see https://github.com/tabs/MyActions_Chaego

**Comment by lukemin** [comment]
请问一下你都是同步了谁的脚本啊？
https://github.com/panghu999/jd_scripts
https://github.com/hongyunfei/jd_scripts
https://github.com/star261/jd
推荐上面几个的，更新比较快。
