### ISSUE TITLE
大佬，求搬运

### ISSUE THREAD

**Issue by anakinlee99** [wuzhi04/MyActions#3]
① 京喜88红包
活动地址：京喜APP-我的-领88元红包
活动时间：2021-4-22至2021-6-30
https://raw.githubusercontent.com/zooPanda/zoo/dev/zooJx88hongbao.js

② 京喜牧场刷金币

https://raw.githubusercontent.com/moposmall/Script/main/Me/jx_mc_coin.js

请大佬有空看一下，可不可以搬运过来，谢谢！

**Comment by wuzhi04** [comment]
惊喜红包有了，刷金币明天加
