### ISSUE TITLE
jd_ddopk.js（京享值pk）脚本不跑了

### ISSUE THREAD

**Issue by xiaoyang19941021** [wuzhi04/MyActions#32]
日志如下：
token获取成功
{"errorCode":null,"errorMessage":null,"currentTime":1624689027571,"data":{"lkEPin":"06b1a42c1214a9202d1421487e49c7870f296a206a12473f57d63d95f3be0534","lkToken":"01f785b19f324404a4f46c4216c327b2"},"success":true}
当前pin（pk码）：[object Object]
查询[object Object]分数
获取Pk列表
上传pk码: [object Object]
[object Object]上传成功
我的京享值:0

**Comment by wuzhi04** [comment]
已经失效，马上撤除
