### ISSUE TITLE
一用github拉取就封我号，太难了，嘤嘤嘤

### ISSUE THREAD

**Issue by zwy98280** [wuzhi04/MyActions#33]

**Comment by wangyunqing198801** [comment]
docker

**Comment by 375785353** [comment]
封号是永久封的吗？？封号了咋办？

**Comment by zwy98280** [comment]
> 封号是永久封的吗？？封号了咋办？

永久的，封号了凉拌呗，重新创一个

**Comment by yunv7** [comment]
而且看现在这个库里actions也没了  估计是封了actions

**Comment by zwy98280** [comment]
> 而且看现在这个库里actions也没了 估计是封了actions

大佬的群又没发话

**Comment by wuzhi04** [comment]
先注册github，之后fork几个别的项目，静置两天账号，然后同步之后不要立即运行，有效防ban
