### ISSUE TITLE
推送询问

### ISSUE THREAD

**Issue by nmy-github** [wuzhi04/MyActions#36]
树叶大哥,你这个钉钉推送和酷推邮箱推送还能用吗?没有关闭吧?
我设置了没有推送,只有tg推送
所以询问一下.

**Comment by wuzhi04** [comment]
1.树叶已经很久不维护这个项目了，暂交由我维护
2.酷推因为之前他QQ封禁非常严重，目前基本上已经停用。钉钉推送理论上是正常的不过我没测试我自己用的是企业微信

**Comment by tiddlerhxy** [comment]
钉钉可以，我就是用的钉钉

**Comment by tiddlerhxy** [comment]
钉钉可以，我就是用的钉钉
