### ISSUE TITLE
容器一直重启，查看docker logs ，发现更新完最新的script就会重启容器，是不是scripts有bug

### ISSUE THREAD

**Issue by lyskywalker** [wuzhi04/MyActions#44]
容器一直重启，查看docker logs ，发现更新完最新的script就会重启容器，是不是scripts有bug

**Comment by wuzhi04** [comment]
暂时把-e ENABLE_HANGUP=false \改为false

**Comment by wuzhi04** [comment]
挂机脚本有问题还没修，暂时这样下午有空更新一下
