### ISSUE TITLE
已查到原因，但是有疑问，求解答

### ISSUE THREAD

**Issue by king6207** [wuzhi04/MyActions#48]
免费用户每个月只能执行2000次的action，Pro用户每月3000次action。经过对比查询才发现是这个执行次数超限。
关键问题是每天workflows内的yml执行次数非常多，一个月2000次严重不够，3000次肯定也不够。
您是如何解决这个执行次数闲置的？或者在action设置里是如何设置的，为何我的执行次数一天就非常多次？

**Comment by wuzhi04** [comment]
公开仓库，不要设置私有就没有任何限制了
