### ISSUE TITLE
大佬能搞个云函数吗

### ISSUE THREAD

**Issue by forgiveme0** [wuzhi04/MyActions#54]
GitHub action太容易封号了🥲

**Comment by nmy-github** [comment]
哈哈 我几乎把我所有邮箱都注册github啦,其他都封禁了,,,最后这个 我铤而走险呢

**Comment by chanvvj** [comment]
> 哈哈 我几乎把我所有邮箱都注册github啦,其他都封禁了,,,最后这个 我铤而走险呢

把被封的好注销，可以重新注册，最好养一养再用。

**Comment by nmy-github** [comment]
you

> > 哈哈 我几乎把我所有邮箱都注册github啦,其他都封禁了,,,最后这个 我铤而走险呢
> 
> 把被封的号注销，可以重新注册，最好养一养再用。

有什么注销账号技巧吗

**Comment by wuzhi04** [comment]
云函数没有额外的维护精力，建议搞个小设备跑
