### ISSUE TITLE
脚本会自动领取618活动红包？？

### ISSUE THREAD

**Issue by cmsyun** [wuzhi04/MyActions#6]
每次准备手动领加码红包时就显示今日机会已用完？？？

**Comment by wuzhi04** [comment]
什么意思？有主会场红包领取的脚本

**Comment by cmsyun** [comment]
> 什么意思？有主会场红包领取的脚本

请问是哪个脚本

**Comment by wuzhi04** [comment]
618主会场红包雨？可以抽中88的那个

**Comment by cmsyun** [comment]
> 618主会场红包雨？可以抽中88的那个

好的 感谢

**Comment by cmsyun** [comment]
> 没事，我不清楚你说的是什么红包，我记得是有一个可以每晚上抽主会场红包雨的脚本，能直接领红包的应该就是那个了

这个 每天三次机会的
![image](https://user-images.githubusercontent.com/62837258/122326013-2fc13a00-cf5e-11eb-8bcb-9c428a6e100b.png)

**Comment by cmsyun** [comment]
> 没事，我不清楚你说的是什么红包，我记得是有一个可以每晚上抽主会场红包雨的脚本，能直接领红包的应该就是那个了

这个 每天三次机会的 
![image](https://user-images.githubusercontent.com/62837258/122327061-d8bc6480-cf5f-11eb-93df-f6832148ebba.png)

**Comment by wuzhi04** [comment]
那不太清楚，建议确保CK有无外泄
