### ISSUE TITLE
我删除都重装系统了还是访问不了

### ISSUE THREAD

**Issue by Imcaochang** [wuzhi04/MyActions#6]
使用的这个命令一键安装的  安全组也全放开全0.0.0.0   但还是访问不了docker 容器也有在运行 wget -q https://wuzhi03.coding.net/p/dj/d/readme/git/raw/main/jd-base.sh -O jd-base.sh && chmod +x jd-base.sh && ./jd-base.sh

![image](https://user-images.githubusercontent.com/65030327/121302286-0e43cb00-c92c-11eb-82f0-9c3dc78862f9.png)

**Comment by wuzhi04** [comment]
那就别用一键，自己理解每条命令的意思手动安装
