### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by 1668458964** [wuzhi04/MyActions#68]
老大  用青龙面板拉了你的库以后不能运行是咋回事 日志说缺少模块
![QQ截图20210814185500](https://user-images.githubusercontent.com/58337621/129444219-59c11aee-c690-4edf-aef2-8423f9bf4e71.png)
![QQ截图20210814185610](https://user-images.githubusercontent.com/58337621/129444221-d0a93bf2-1cb5-455d-9192-d6b790932a39.png)

**Comment by wuzhi04** [comment]
缺少哪个模块装哪个吧
