### ISSUE TITLE
锦鲤红包

### ISSUE THREAD

**Issue by wangmeng23** [wuzhi04/MyActions#71]
最近发现京东锦鲤红包助力消失查看日志并无异常
猜测
1.面板可能存在漏洞cookie被他人盗取❌（将原有的cookie失效，在本地运行依旧助力消失）
2.其他脚本留有后门❓（修改定时为0:10助力还在）

**Comment by kk1906** [comment]
那个脚本jd_redPacket替换成其他的大佬的就有助力了

**Comment by wuzhi04** [comment]
这两天私事缠身，我会尽快解决
