### ISSUE TITLE
无法推送QQ信息

### ISSUE THREAD

**Issue by xuyien97** [wuzhi04/MyActions#72]
url: `${GOBOT_URL}?access_token=${GOBOT_TOKEN}&${GOBOT_QQ}`,

**Comment by xuyien97** [comment]
> ```
>     url: `${GOBOT_URL}?access_token=${GOBOT_TOKEN}&${GOBOT_QQ}`,
> ```
需要在 ${GOBOT_QQ} 前 添加  user_id 或者  group_id

**Comment by xuyien97** [comment]
> > ```
> >     url: `${GOBOT_URL}?access_token=${GOBOT_TOKEN}&${GOBOT_QQ}`,
> > ```
> 
> 需要在 ${GOBOT_QQ} 前 添加 user_id 或者 group_id

 url: `${GOBOT_URL}?access_token=${GOBOT_TOKEN}&user_id=${GOBOT_QQ}`,

**Comment by wuzhi04** [comment]
这个我只是搬过来，暂时还没时间看怎么用 抽空搞搞或者直接pull requests过来也可以
