### ISSUE TITLE
如下功能脚本无效用

### ISSUE THREAD

**Issue by wifisky-feilian** [wuzhi04/MyActions#76]
如下功能脚本无效用：
1、京东领券签到、点点券、锦鲤红包、券后9.9-点击拿奖励；
2、京东签到图形验证有时候出现全部失败
--------------------------------------------------------------------------------------------------------------------------------------------
3、惊喜财富岛（前几天脚本还有效用呢，能签到、能接待的，当时就是不能升级建筑和不能浏览1次爆款活动，现在不能签到领奖、不能接待游客，不能浏览1次爆款活动，不能自动升级建筑）；
4、惊喜红包签到，不能自动开启宝箱

**Comment by wuzhi04** [comment]
1.这些签到需要sign，目前是通过ddo提供的免费获取sign的接口，获取高峰期可能获取失败，导致未签到
2.图形验证人手也有失败的时候，更何况代码去尝试
3，财富岛刚搬运最新的应该可以了
4，后续如有更新会搬
