### ISSUE TITLE
扫码获取的COOKIES不到一周全失效，今天用脚本里的扫码获取COOKIES，点几JD的APP”确认登录“后，提示“请升级到最新的版本的手机京东”

### ISSUE THREAD

**Issue by wifisky-feilian** [wuzhi04/MyActions#78]
扫码获取的COOKIES不到一周全失效，今天用脚本里的扫码获取COOKIES，点几JD的APP”确认登录“后，提示“请升级到最新的版本的手机京东”，建议修复一下，辛苦了~

**Comment by wuzhi04** [comment]
全网无解，无法修复

**Comment by wifisky-feilian** [comment]
> 全网无解，无法修复

0825京东扫码修复.docx
1. 进入容器，新建一个终端
 
2. 输入 npm install http-proxy
3. 打开配置文件，加入环境变量：
export HTTP_PROXY="http://127.0.0.1:3333/"
 
4. 关闭容器，编辑端口，映射3333端口为4444
5. 启动容器
6. 手机端连接wifi，设置手动代理为 你的服务器地址：4444

某Q群有人发布了方法，本人没有测试，不知道管用不，不过看起来挺麻烦~
