### ISSUE TITLE
jd_zoo火爆问题~~~

### ISSUE THREAD

**Issue by xiaoyang19941021** [wuzhi04/MyActions#8]
该账户脚本执行任务火爆，暂停执行任务，请手动做任务或者等待解决脚本火爆问题

**Comment by wuzhi04** [comment]
yangtingxiao大哥的算法已经停止更新，我用的是他最后一版的算法配合动态获取token，如不行也没办法了，打怪兽已经过去了

**Comment by winsphinx** [comment]
没办法了，目前手动也要图形验证了
