### ISSUE TITLE
给个云函数教程

### ISSUE THREAD

**Issue by doudou0628** [wuzhi04/MyActions#8]
大哥求出个云函数教程，4个账号被封了，今天刚注册个运行了不到1分钟又被封了，太难了

**Comment by wuzhi04** [comment]
云函数我个人无精力维护，所以暂无

**Comment by anakinlee99** [comment]
云函数可以去看看这位大佬的
https://github.com/zero205/JD_tencent_scf
但是云函数局限还是太大了，还是建议使用docker运行。
