### ISSUE TITLE
无法下载jd-base

### ISSUE THREAD

**Issue by NittaAkio** [wuzhi04/MyActions#9]
一键命令：wget -q https://wuzhi03.coding.net/p/dj/d/readme/git/raw/main/jd-base.sh -O jd-base.sh && chmod +x jd-base.sh && ./jd-base.sh
下载不了jd-base.sh

**Comment by wuzhi04** [comment]
这是coding的地址国内一般都可以访问，实在不行就手动拉取容器然后部署
