### ISSUE TITLE
wuzhi04你用的是lxk0301的源吗吧？lxk0301最后一版源码我6个账号互相之间还能助力呢，为啥用你这个代码，我这6个账号都不互相助力了呢？不互相助力了搞得我所有账号下的活动都生产很慢很慢的

### ISSUE THREAD

**Issue by wifisky-feilian** [wuzhi04/MyActions#91]
wuzhi04你用的是lxk0301的源吗吧？lxk0301最后一版源码我6个账号互相之间还能助力呢，为啥用你这个代码，我这6个账号都不互相助力了呢？不互相助力了搞得我所有账号下的活动都生产很慢很慢的，竟然为什么呢？什么原因呢？

**Comment by wuzhi04** [comment]
自己先检查是不是填对了互助码，LXK的老旧脚本都没有循环互助，因为互助码固定不变所以需要自己填入。目前大部分新的脚本都有内部循环互助。
