### ISSUE TITLE
按照建议的教程操作，代码同步失败

### ISSUE THREAD

**Issue by CallMeHiker** [wuzhi04/MyActions#92]
按照你建议的使用教程操作，代码同步失败，
Found online and idle hosted runner in the current repository's organization account that matches the required labels: 'ubuntu-latest'
Waiting for a Hosted runner in the 'organization' to pick this job...
Job is waiting for a hosted runner to come online.
Job is about to start running on the hosted runner: Hosted Agent (hosted)
是什么原因呢，在那个作者的项目提issue没回复

**Comment by wuzhi04** [comment]
什么平台  报错截图

**Comment by CallMeHiker** [comment]
就是用Git action，上面的就是整个报错提示
![image](https://user-images.githubusercontent.com/16526833/133566281-db415385-4fd3-4852-abba-dea41b4fb677.png)

**Comment by CallMeHiker** [comment]
根据 https://github.com/Muzhen01/Readme 这个教程来弄的

**Comment by wuzhi04** [comment]
这个不太清楚，换号重试吧
