### ISSUE TITLE
每日签到为啥不行了，运行不下去

### ISSUE THREAD

**Issue by 298087776** [wuzhi04/MyActions#93]

**Comment by wuzhi04** [comment]
什么平台 报错截图

**Comment by 298087776** [comment]
> 什么平台 报错截图

Run node onlyOneExecute.js，这个运行一直执行不下去

**Comment by 298087776** [comment]
> 什么平台 报错截图

![image](https://user-images.githubusercontent.com/77576457/133545257-82345bac-ca6d-490e-b738-8b5cb83de169.png)

**Comment by 298087776** [comment]
> 什么平台 报错截图

![image](https://user-images.githubusercontent.com/77576457/133547391-60cfcda8-34c5-48e7-9928-7f47c3b36628.png)
新签到，到这里就卡了，运行不下去

**Comment by 298087776** [comment]
> > 什么平台 报错截图
> 
> ![image](https://user-images.githubusercontent.com/77576457/133547391-60cfcda8-34c5-48e7-9928-7f47c3b36628.png)
> 新签到，到这里就卡了，运行不下去

![image](https://user-images.githubusercontent.com/77576457/133547465-8af2becd-23b9-4851-8edc-fcbf32688f2f.png)

**Comment by wuzhi04** [comment]
github用户？，后续我搞一个github签到专版试试看吧

**Comment by wuzhi04** [comment]
明白了，新的签到需要依赖，github无法运行

**Comment by 298087776** [comment]
> 明白了，新的签到需要依赖，github无法运行

那要到哪个平台才能运行？
